# Generated by Django 2.2.5 on 2020-06-29 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0003_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='current_date',
            new_name='created_date',
        ),
    ]
