# Generated by Django 2.2.5 on 2020-07-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0004_auto_20200629_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
        ),
    ]
